version: "7"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    restart: always
    volumes: 
      - ./cache:/data
volumes:
  cache:
    driver: local